# https://docs.gitlab.com/ee/ci/quick_start/index.html
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
image: python:3.12

stages:
  - pre-commit
  - test

pre-commit-job:
  tags:
    - Debian
    - Docker
  stage: pre-commit
  before_script:
    - apt update
    - apt install -y python3-lib2to3 libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
    - python -m pip install --upgrade pip
    - pip install pre-commit
  script:
    - pip install --editable ".[format]"
    - pre-commit install
    - pre-commit run --all-files


test-job:
  tags:
    - Debian
    - Docker
  stage: test
  before_script:
    - apt update
    - apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
    - python -m pip install --upgrade pip
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --editable ".[test]"
  script:
    - coverage run -m pytest --junitxml=test_report.xml
    - coverage xml -o coverage_report.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage_report.xml
      junit: test_report.xml
  needs:
    - pre-commit-job

